/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.blackhorse.kronos.frames;

import com.blackhorse.kronos.Functions;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;

/**
 *
 * @author whitesnake
 */
public class PdfToImgFrame extends javax.swing.JFrame {
    
    private final List<File> pdfFiles;
    DefaultListModel<String> model = new DefaultListModel<>();
    Functions fun = new Functions();
    private static PdfToImgFrame instancia;

    /**
     * Creates new form PdfToImgFrame
     */
    public PdfToImgFrame() {
        this.pdfFiles = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uploadPTIButton = new javax.swing.JButton();
        convertPTIButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        filePTIWord = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDF a Imágenes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        uploadPTIButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        uploadPTIButton.setText("Cargar archivo");
        uploadPTIButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uploadPTIButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uploadPTIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPTIButtonActionPerformed(evt);
            }
        });

        convertPTIButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        convertPTIButton.setText("Convertir a Imágenes");
        convertPTIButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        convertPTIButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        convertPTIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertPTIButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(filePTIWord);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadPTIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertPTIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uploadPTIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(convertPTIButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadPTIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadPTIButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File[] selectedFiles = fileChooser.getSelectedFiles();
            for (File file : selectedFiles) {
                if (file.getName().endsWith(".pdf")) {
                    pdfFiles.add(file);
                    filePTIWord.setModel(model);
                    model.addElement(file.toString());
                }else{
                    JOptionPane.showMessageDialog(null, "Formato de archivo incorrecto!");
                }
            }
        }
    }//GEN-LAST:event_uploadPTIButtonActionPerformed

    private void convertPTIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertPTIButtonActionPerformed
        if (!pdfFiles.isEmpty()) {

            for (File pdf : pdfFiles) {

                try (PDDocument document = PDDocument.load(new File(pdf.getAbsolutePath()))) {
                    PDFRenderer pdfRenderer = new PDFRenderer(document);
                    for (int page = 0; page < document.getNumberOfPages(); ++page) {
                        BufferedImage bim = pdfRenderer.renderImageWithDPI(page, 300); // 300 DPI
                        String fileName = "Kronos imagen "+fun.getDate() + " pagina_" + (page + 1) + ".jpg";
                        ImageIO.write(bim, "jpg", new File(fileName));
                    }
                    JOptionPane.showMessageDialog(null, "Archivos PDF combinados exitosamente!");
                    System.out.println("Conversión completada.");
                } catch (IOException e) {
                }

                /*
                // Cargar el archivo PDF
                Document pdfDocument = new Document(pdf.getAbsolutePath());

                // Guardar el archivo PDF como Word
                pdfDocument.save("Kronos word "+fun.getDate()+".docx", SaveFormat.DocX);

                JOptionPane.showMessageDialog(null, "Archivos PDF combinados exitosamente!");
                */
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se han cargado archivos PDF.");
        }
    }//GEN-LAST:event_convertPTIButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        instancia = null;
        dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PdfToImgFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PdfToImgFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PdfToImgFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PdfToImgFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PdfToImgFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertPTIButton;
    private javax.swing.JList<String> filePTIWord;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton uploadPTIButton;
    // End of variables declaration//GEN-END:variables

    public static PdfToImgFrame getInstancia(){
        if (instancia == null){
            instancia = new PdfToImgFrame();
            instancia.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            instancia.setVisible(true);
            
        }
        return instancia;
    }

}
